name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
      
    - name: find apk
      run:  find ./ -regex ".*\.apk\|.*\.aar"
           
       
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
          name:  dowork-debug
          path: app/build/outputs/apk/debug/*.apk
